### ISSUE TITLE
Add support for 'Destructure' configuration options in app settings

### ISSUE THREAD

**Issue by olamartensson** [serilog/serilog-settings-appsettings#20]
I would like to be able to configure Serilog's `Destructure` configuration options like e.g.:
```csharp
Log.Logger = new LoggerConfiguration()
                .Destructure.With<MyCustomDestructuringPolicy>()
                .Destructure.UsingAttributes() // using Destructurama.Attributed
                .CreateLogger();
```
in the app settings XML file like e.g.:
```xml
<appSettings>
    <add key="serilog:using:DestructuringPolicies" value="MyApp.CustomDestructuringPolicies" />
    <add key="serilog:destructure:WithMyCustomDestructuringPolicy" />
    <add key="serilog:using:Destructurama" value="Destructurama.Attributed" />
    <add key="serilog:destructure:UsingAttributes" />
</appSettings>
```

It seems to me this is not possible today.

**Comment by nblumhardt** [comment]
Thanks for the suggestion 👍

**Comment by tsimbalar** [comment]
In order to have aconsistent implementation, it should be similar to serilog/serilog-settings-configuration#110

**Comment by tsimbalar** [comment]
How should generic parameters be specified in order to call `.Destructure.With<MyCustomDestructuringPolicy>()` ? 

I would say staying close to C# would be the best approach (using angle brackets), but in a XML-ish config file, that probably means they would have to be escaped like so : 

```xml
    <add key="serilog:using:DestructuringPolicies" value="MyApp.CustomDestructuringPolicies" />
    <add key="serilog:destructure:With&lt;MyCustomDestructuringPolicy&gt;" />
```

Another option is to not support generic parameters at all in the settings providers, but to add a _non-generic_ version of the method in *Serilog* and having both : 

```csharp
public LoggerConfiguration With<TDestructuringPolicy>()
```

and

```csharp
public LoggerConfiguration With(Type destructuringPolicyType)
```

The first one can be used in C# code, the second one can be used in configuration (I believe there is already support for parameters of type `Type`, but I may be wrong ...).

**Comment by tsimbalar** [comment]
This is being worked on in the [main Serilog repo](https://github.com/serilog/serilog) through : 
- serilog/serilog#1172
- serilog/serilog#1177
- serilog/serilog#1178

**Comment by nblumhardt** [comment]
Looks like this has moved forwards :+1:
