### ISSUE TITLE
Is it possible to use a custom enricher?

### ISSUE THREAD

**Issue by Andrei-Astakhov** [serilog/serilog-settings-appsettings#43]
Hello,
A have a custom enricher that returns the current thread Id. 
`
public class MyEnricher : ILogEventEnricher {
    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory) {
            logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty(
                    "ThreadId", Thread.CurrentThread.ManagedThreadId));
        }
    }
`
How I can add this enricher via AppSettings?

Thank you.

**Comment by tsimbalar** [comment]
Hi,

you can do this yes. Take a look at https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md#method-discovery which has some example.

The important part is: 
- to add an extension method so that your C# code would look like `Enrich.WithCustomWhatever()`
- then `<add key="serilog:using:XXX" value="XXX" />` to specify where to look for this extension method (name of the assembly)
- then provide add something like `<add key="serilog:enrich:WithCustomWhatever" value="" />`

I hope this helps !

**Comment by Andrei-Astakhov** [comment]
Hi,
Thank you for your suggestion and for the link. Now it works.
